import DynamicForm, { withFormHoc } from '@medplus/react-common-components/DynamicForm';
import React from 'react'



const CatalogDynamicForm=(props)=> {
    const {helpers}=props;
    let obj = {
        "htmlElementType": "FORM",
        "id": "CatalogDynamicForm",
        "label": null,
        "name": null,
        "value": null,
        "className": null,
        "readOnly": false,
        "disabled": false,
        "autofocus": false,
        "required": false,
        "style": null,
        "attributes": null,
        "message": null,
        "htmlActions": null,
        "elementSize": null,
        "defaultValue": null,
        "helperText": null,
        "labelClassName": null,
        "htmlGroups": [
            {
                "htmlElementType": "ELEMENTGROUP",
                "id": "group1",
                "label": null,
                "name": null,
                "value": null,
                "className": "row g-3",
                "readOnly": false,
                "disabled": false,
                "autofocus": false,
                "required": false,
                "style": null,
                "attributes": null,
                "message": null,
                "htmlActions": null,
                "elementSize": null,
                "defaultValue": null,
                "helperText": null,
                "labelClassName": null,
                "groups": null,
                "groupElements": [
                    {
                        "htmlElementType": "DATALIST",
                        "id": "selectVariant",
                        "label": "Select Variant",
                        "name": null,
                        "value": null,
                        "onInputChangeEnable": true,
                        "className": null,
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": true,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "helperText": null,
                        "labelClassName": "col-1 w-100",
                        "regex": null,
                        "minLength": null,
                        "maxLength": 30,
                        "min": null,
                        "max": null,
                        "placeholder": null,
                        "hidden": false,
                        "value" : ["50mg"]
                    },
                    {
                        "htmlElementType": "INPUT",
                        "id": "qtyInPacks",
                        "label": "Enter Quantity in Packs",
                        "name": null,
                        "value": null,
                        "className": null,
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": true,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "helperText": null,
                        "labelClassName": "col-4",
                        "type": "text",
                        "placeholder": null,
                        "hidden": false
                    }, {
                        "htmlElementType": "BUTTON",
                        "id": "addProduct",
                        "label": "Add to Bag",
                        "name": null,
                        "value": null,
                        "className": "col-2 btn-success btn-sm me-2",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": {"height":"50px"},
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "src": null,
                        "href": null,
                        "reset": false,
                        "submit": true,
                        "hidden": false
                    },
                    {
                        "htmlElementType": "BUTTON",
                        "id": "becomeMember",
                        "label": "Become Member for ₹50",
                        "name": null,
                        "value": null,
                        "className": "col-4 btn-sm btn-outline-primary",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": {"height":"50px"},
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "src": null,
                        "href": null,
                        "reset": false,
                        "submit": false,
                        "hidden": false
                    }
                ]
            }
        ],
        "notes": null,
        "atleastOneFieldRequired": false,
        "submitDisabled": false,
        "hidden": false
    };
  return (
    <DynamicForm formJson={obj} helpers={helpers}/>
  )
}

export default withFormHoc(CatalogDynamicForm) 