import DynamicForm,{ withFormHoc } from '@medplus/react-common-components/DynamicForm';
import React from 'react'



const DeliveryDetailsForm = (props) => {
  const { helpers } = props;
  let obj = {
    "htmlElementType": "FORM",
    "id": "DeliveryForm",
    "label": null,
    "name": null,
    "value": null,
    "className": null,
    "readOnly": false,
    "disabled": false,
    "autofocus": false,
    "required": false,
    "style": null,
    "attributes": null,
    "message": null,
    "htmlActions": null,
    "elementSize": null,
    "defaultValue": null,
    "helperText": null,
    "labelClassName": null,
    "htmlGroups": [
      {
        "htmlElementType": "ELEMENTGROUP",
        "id": "group1",
        "label": null,
        "name": null,
        "value": null,
        "className": "row g-3",
        "readOnly": false,
        "disabled": false,
        "autofocus": false,
        "required": false,
        "style": null,
        "attributes": null,
        "message": null,
        "htmlActions": null,
        "elementSize": null,
        "defaultValue": null,
        "helperText": null,
        "labelClassName": null,
        "groups": null,
        "groupElements": [
          {
            "htmlElementType": "INPUT",
            "id": "CustomerName",
            "label": "Customer Name",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "ReceiversName",
            "label": "Receiver's Name",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "MedplusID",
            "label": "Medplus ID",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "Address",
            "label": "Address",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-12",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "City",
            "label": "City",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "State",
            "label": "State",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "Pincode",
            "label": "Pincode",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "EmailID",
            "label": "EmailID",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "INPUT",
            "id": "MobileNumber",
            "label": "Mobile Number",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-4",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
          {
            "htmlElementType": "RADIO",
            "id": "Card Order",
            "label": "Card Order",
            "name": null,
            "value": null,
            "className": "col-4",
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": "N",
            "helperText": null,
            "labelClassName": "d-flex text-muted mb-0 font-12",
            "values": [
                {
                    "htmlElementType": "OPTION",
                    "id": "rcmYesOption",
                    "label": "Yes",
                    "name": "",
                    "value": "Y",
                    "className": null,
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "displayValue": "Yes",
                    "selected": false,
                    "hidden": false
                },
                {
                    "htmlElementType": "OPTION",
                    "id": "rcmNoOption",
                    "label": "No",
                    "name": "",
                    "value": "N",
                    "className": null,
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "displayValue": "No",
                    "selected": true,
                    "hidden": false
                }
            ],
            "hidden": false
        },
          {
            "htmlElementType": "INPUT",
            "id": "customerStoreId",
            "label": "customer Store Id",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": true,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "helperText": null,
            "labelClassName": "col-12",
            "type": "text",
            "placeholder": null,
            "hidden": false
          },
        ]
      },
    ],
        "notes": null,
        "atleastOneFieldRequired": false,
        "submitDisabled": false,
        "hidden": false
  }
  return (
    <DynamicForm formJson={obj} helpers={helpers}/>
  )
}

export default withFormHoc(DeliveryDetailsForm)