export const Roles={
    ROLE_CRM_MEDI_ASSISIT : 'ROLE_CRM_MEDI_ASSISIT',
    ROLE_CRM_CUSTOMER_CREATE : 'ROLE_CRM_CUSTOMER_CREATE',
    ROLE_CRM_LAB_VIEW_SUBSCRIPTION : 'ROLE_CRM_LAB_VIEW_SUBSCRIPTION',
    ROLE_SUBSCRIPTION_BULK_UPLOAD : 'ROLE_SUBSCRIPTION_BULK_UPLOAD',
    ROLE_CRM_UPLOAD_SUBSCRIPTIONS : 'ROLE_CRM_UPLOAD_SUBSCRIPTIONS',
    ROLE_CRM_DOWNLOAD_SUBSCRIPTIONS : 'ROLE_CRM_DOWNLOAD_SUBSCRIPTIONS',
    ROLE_CRM_LAB_ORDER_REGENERATE : 'ROLE_CRM_LAB_ORDER_REGENERATE',
    ROLE_CRM_NON_MA_MEMBER_EDIT : 'ROLE_CRM_NON_MA_MEMBER_EDIT',
    ROLE_CRM_REGISTERED_DOCTOR_BULK : 'ROLE_CRM_REGISTERED_DOCTOR_BULK',
    ROLE_CRM_MEDPLUS_SUBSCRIPTION_CASH : "ROLE_CRM_MEDPLUS_SUBSCRIPTION_CASH",
    ROLE_CRM_LAB_SUBSCRIPTION_PLAN_ADD : "ROLE_CRM_LAB_SUBSCRIPTION_PLAN_ADD",
    ROLE_CRM_LAB_SUBSCRIPTION_PLAN_CANCEL : "ROLE_CRM_LAB_SUBSCRIPTION_PLAN_CANCEL",
    ROLE_CRM_MA_MEMBER_EDIT : "ROLE_CRM_MA_MEMBER_EDIT",
    ROLE_CRM_LAB_SUBSCRIPTION_PLAN_RENEW : "ROLE_CRM_LAB_SUBSCRIPTION_PLAN_RENEW",
    ROLE_CRM_ORDER_CREATE : "ROLE_CRM_ORDER_CREATE",
    ROLE_CRM_LAB_FRONT_OFFICE_ORDER_CREATE : "ROLE_CRM_LAB_FRONT_OFFICE_ORDER_CREATE",
    ROLE_CRM_PHLEBOTOMIST_PATHLAB_AGENT : "ROLE_CRM_PHLEBOTOMIST_PATHLAB_AGENT",
    ROLE_CRM_LAB_ORDER_CREATE : "ROLE_CRM_LAB_ORDER_CREATE",
    ROLE_CRM_REGISTERED_DOCTOR: "ROLE_CRM_REGISTERED_DOCTOR"

}