
const FormHelpers = () => {

    const getCancelForm = (orderCancelReasonType, helpers) => {
        let cancelFormOptions = [];
        orderCancelReasonType.map((reason, index) => {
            cancelFormOptions.push(helpers.createOption(reason, reason, reason));
        });
        const cancelForm = {
            "htmlElementType": "FORM",
            "id": "cancelForm",
            // "label": "Cancel Order",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12 mb-3",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "DATALIST",
                            "id": "reasonType",
                            "label": "Reason Type",
                            "name": "reasonType",
                            "value": null,
                            "onInputChangeEnable": false,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "dataListClassName":"custom-datagrid",
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-12",
                            "regex": null,
                            "minLength": null,
                            "maxLength": null,
                            "min": null,
                            "max": null,
                            "placeholder": null,
                            "hidden": false,
                            "values": cancelFormOptions
                        },
                        {
                            "htmlElementType": "TEXTAREA",
                            "id": "cancelReason",
                            "label": "Reason To Cancel",
                            "name": "cancelReason",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": "Enter Reason To Cancel",
                            "hidden": true
                        },
                      
                    ]
                },{

                    "htmlElementType": "ELEMENTGROUP",
                        "id": "group2",
                        "label": null,
                        "value": null,
                        "className": "modal-footer justify-content-center",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "src": null,
                        "href": null,
                        "reset": false,
                        "submit": true,
                        "hidden": false,
                        "groupElements":[
                            {
                                "htmlElementType": "BUTTON",
                                "id": "closeModal",
                                "label": "Close",
                                "value": null,
                                "className": "ms-2 col-3 brand-secondary btn-light",
                                "readOnly": false,
                                "disabled": false,
                                "autofocus": false,
                                "required": false,
                                "style": null,
                                "attributes": null,
                                "message": null,
                                "htmlActions": null,
                                "elementSize": null,
                                "defaultValue": null,
                                "helperText": null,
                                "labelClassName": null,
                                "src": null,
                                "href": null,
                                "reset": false,
                                "submit": false,
                                "hidden": false
                            },
                            {
                                    "htmlElementType": "BUTTON",
                                    "id": "submitCancelForm",
                                    "label": "Yes, Cancel this order",
                                    "name": null,
                                    "value": null,
                                    "className": "ms-2 col-3 btn-brand",
                                    "readOnly": false,
                                    "disabled": false,
                                    "autofocus": false,
                                    "required": false,
                                    "style": null,
                                    "attributes": null,
                                    "message": null,
                                    "htmlActions": null,
                                    "elementSize": null,
                                    "defaultValue": null,
                                    "helperText": null,
                                    "labelClassName": null,
                                    "src": null,
                                    "href": null,
                                    "reset": false,
                                    "submit": true,
                                    "hidden": false
                            }
                        ]
                }
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": true,
            "hidden": false
        };
        return cancelForm;
    }

    const getLabCancelForm = ( helpers) => {
        const labCancelForm = {
            "htmlElementType": "FORM",
            "id": "labCancelForm",
            "label": "Cancel Order",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 mb-4",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "TEXTAREA",
                            "id": "cancelReason",
                            "label": "Reason To Cancel",
                            "name": "cancelReason",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": "Enter Reason To Cancel",
                            "hidden": false
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitLabCancelForm",
                            "label": "Yes, Cancel this order",
                            "name": null,
                            "value": null,
                            "className": "ms-2 col-3 btn-dark",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ]
                }
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": true,
            "hidden": false
        };
        return labCancelForm;
    }

    const getAddPatientDetailsForm = (orderInfo, from) => {
        const addPatientDetailsForm = {
            "htmlElementType": "FORM",
            "id": "addPatientDetailsForm",
            "label": null,
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "INPUT",
                            "id": "patientName",
                            "label": "Patient Name",
                            "name": "patientName",
                            "value": orderInfo.patientName,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Patient Name',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "patientAge",
                            "label": "Patient Age",
                            "name": "patientAge",
                            "value": orderInfo.patientAge,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "^[0-9]{1,2}$",
                            "placeholder": 'Enter patient Age',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "doctorName",
                            "label": "Doctor Name",
                            "name": "doctorName",
                            "value": orderInfo.doctorName,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-12",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Doctor Name',
                            "hidden": false
                        }
                    ]
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group2",
                    "label": null,
                    "value": null,
                    "className": "modal-footer justify-content-center",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "src": null,
                    "href": null,
                    "reset": false,
                    "submit": true,
                    "hidden": false,
                    "groupElements":[
                        {
                            "htmlElementType": "BUTTON",
                            "id": "closeModal",
                            "label": "Close",
                            "value": null,
                            "className": "ms-2 col-3 brand-secondary btn-light",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitAddPatientDetailsForm",
                            "label": from == 'editOrderDetailsForm' ? "Update" : "Submit",
                            "value": null,
                            "className": from == 'editOrderDetailsForm'? "ms-2 col-3 btn-primary":"ms-2 col-3 btn-brand",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ]
                },
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return addPatientDetailsForm;
    }

    const getEditOrderDetailsForm = (orderInfo, mobileNo) => {
        const editOrderDetailsForm = {
            "htmlElementType": "FORM",
            "id": "editOrderDetailsForm",
            "label": null,
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "INPUT",
                            "id": "patientName",
                            "label": "Patient Name",
                            "name": "patientName",
                            "value": orderInfo.patientName,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Patient Name',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "patientAge",
                            "label": "Patient Age",
                            "name": "patientAge",
                            "value": orderInfo.patientAge,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "^[0-9]{1,2}$",
                            "placeholder": 'Enter patient Age',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "doctorName",
                            "label": "Doctor Name",
                            "name": "doctorName",
                            "value": orderInfo.doctorName,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Doctor Name',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "mobileNum",
                            "label": "Mobile Number",
                            "name": "mobileNum",
                            "value": mobileNo,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": null,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "TEXTAREA",
                            "id": "editAddress",
                            "label": "Address",
                            "name": "editAddress",
                            "value": orderInfo.shipmentOmsAddress.addressLine1,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": null,
                            "hidden": false
                        }
                    ]
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group2",
                    "label": null,
                    "value": null,
                    "className": "modal-footer justify-content-center",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "src": null,
                    "href": null,
                    "reset": false,
                    "submit": true,
                    "hidden": false,
                    "groupElements":[
                        {
                            "htmlElementType": "BUTTON",
                            "id": "closeModal",
                            "label": "Close",
                            "value": null,
                            "className": "ms-2 col-3 brand-secondary btn-light",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitEditOrderDetailsForm",
                            "label": "Update",
                            "value": null,
                            "className": "ms-2 col-3 btn-brand",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ]
                },
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return editOrderDetailsForm;
    }

    const getRescheduleDeliveryForm = (helpers) => {
        let rescheduleReasons = {
            'DAMAGED': 'Damaged',
            'NOT_INTERESTED': 'Not interested',
            'NEXT_DAY': 'Next day',
            'UNAVAILABLE': 'Unavailable',
            'INVALID_ADDRESS': 'Invalid address',
            'ADDRESS_CHANGED': 'Address changed',
            'OTHER': 'Other'
        };
        let rescheduleReasonOptions = [];
        Object.keys(rescheduleReasons).map((key, index) => {
            if (index === 0) {
                rescheduleReasonOptions.push(helpers.createOption(key, rescheduleReasons[key], key, true));
            } else {
                rescheduleReasonOptions.push(helpers.createOption(key, rescheduleReasons[key], key));
            }
        });
        const rescheduleForm = {
            "htmlElementType": "FORM",
            "id": "rescheduleDeliveryForm",
            "label": null,
            "name": null,
            "className": null,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "className": "row g-3 p-12",
                    "autofocus": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "DATALIST",
                            "id": "reasonType",
                            "label": "Reason Type",
                            "name": "reasonType",
                            "value": null,
                            "onInputChangeEnable": false,
                            "className": null,
                            "dataListClassName":"custom-datagrid",
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "helperText": null,
                            "labelClassName": null,
                            "values": rescheduleReasonOptions
                        },
                        {
                            "htmlElementType": "TEXTAREA",
                            "id": "comment",
                            "label": "Comment",
                            "name": "comment",
                            "value": "",
                            "className": null,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "helperText": null,
                            "labelClassName": null,
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "placeholder": "Enter Comment",
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "rescheduleDate",
                            "label": "Reschedule date",
                            "name": "rescheduleDate",
                            "value": "",
                            "type": "datetime-local",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "min": new Date().toISOString().slice(0, -8)
                        }
                    ]
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group2",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "modal-footer justify-content-center",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements":[
                        {
                            "htmlElementType": "BUTTON",
                            "id": "closeModal",
                            "label": "Close",
                            "value": null,
                            "className": "ms-2 col-3 brand-secondary btn-light",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": false,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitRescheduleDeliveryForm",
                            "label": "Submit",
                            "value": null,
                            "className": "ms-2 col-3 btn-brand",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ]
                }
            ],
            "submitDisabled": true,
        };
        return rescheduleForm;
    }

    const getSelectSmsForm = (smsOptions, helpers) => {
        let selectSmsOptions = [];
        {smsOptions && Object.entries(smsOptions).map(([key, value]) => {
            selectSmsOptions.push(helpers.createOption(key, value, key))
        })}
        const selectSmsForm = {
            "htmlElementType": "FORM",
            "id": "sendSmsForm",
            "name": null,
            "value": null,
            "className": "input-group",
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "col-8",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "DATALIST",
                            "id": "smsSelected",
                            "label": "Select SMS",
                            "name": "reasonType",
                            "value": null,
                            "onInputChangeEnable": false,
                            "className": " border-radius-right-clear form-control",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "dataListClassName":"custom-datagrid w-100",
                            // "labelClassName": "w-100",
                            "regex": null,
                            "minLength": null,
                            "maxLength": null,
                            "min": null,
                            "max": null,
                            "placeholder": null,
                            "hidden": false,
                            "values": selectSmsOptions
                        }
                    ],
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group2",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "input-group-append col-4",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitSmsForm",
                            "label": "Send",
                            "name": null,
                            "value": null,
                            "className": "btn-send h-100 w-100",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "variant":' ',
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ],
                }
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return selectSmsForm;
    }

    const getLabOrderRefundFormForCard = () => {
        const getLabOrderRefundFormForCard = {
            "htmlElementType": "FORM",
            "id": "getLabOrderRefundFormForCard",
            "label": null,
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "INPUT",
                            "id": "transactionId",
                            "label": "Transaction Id",
                            "name": "transactionId",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 64,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Transaction Id',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "cardNo",
                            "label": "Card Number",
                            "name": "cardNo",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-6",
                            "regex": "",
                            "maxLength": 16,
                            "placeholder": 'Enter Card Number',
                            "hidden": false
                        },
                        {
                            "htmlElementType": "INPUT",
                            "id": "deviceId",
                            "label": "Device Id",
                            "name": "deviceId",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-12",
                            "regex": "",
                            "minLength": null,
                            "maxLength": 50,
                            "min": 1,
                            "max": null,
                            "placeholder": 'Enter Device Id',
                            "hidden": false
                        }
                    ]
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group2",
                    "label": "Please confirm to complete the refund",
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements" : []
                },
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group3",
                    "label": null,
                    "value": null,
                    "className": "modal-footer justify-content-center",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "src": null,
                    "href": null,
                    "reset": false,
                    "submit": true,
                    "hidden": false,
                    "groupElements":[
                        {
                            "htmlElementType": "BUTTON",
                            "id": "closeModal",
                            "label": "Close",
                            "value": null,
                            "className": "ms-2 col-3 brand-secondary btn-light",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "submitRefundDetails",
                            "label": "Submit",
                            "value": null,
                            "className": "ms-2 col-3 btn-brand",
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": false,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "src": null,
                            "href": null,
                            "reset": false,
                            "submit": true,
                            "hidden": false
                        }
                    ]
                },
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": false,
            "hidden": false
        };
        return getLabOrderRefundFormForCard;
    }
    
    const getCFPInfoForm = () => {
        const cfpInfoForm = {
            "htmlElementType": "FORM",
            "id": "cfpInfoForm",
            "label": "Select Daterange",
            "labelClassName": "h6 custom-fieldset mb-2",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "className": "row g-3",
                    "groupElements": [
                        {
                            "htmlElementType": "DATERANGE",
                            "id": "dateRange",
                            "label": "From Date-To Date",
                            "type": "date",
                            "attributes": {placeholderText: "Date Range (mm dd,yyyy)"},
                            "labelClassName": "col-6",
                            "startDate": new Date(),
                            "endDate": new Date()
                        },
                        {
                            "htmlElementType": "BUTTON",
                            "id": "cfpSubmit",
                            "label": "Submit",
                            "className": "col-2 btn btn-sm btn-dark",
                            "submit": true,
                        }
                    ]
                }
            ],
        };
        return cfpInfoForm;
    }

    const getDoctorRegistrationForm = (helpers) => {
        let options=[];
        options.push(helpers.createOption("checkDetails", "Check Details", "checkDetails", true))
        options.push(helpers.createOption("regDoc", "Register Doctor","regDoc"))
        const doctoreRegistrationForm = {
            "htmlElementType": "FORM",
            "id": "doctorRegistrationForm",
            "label": "Upload For",
            "labelClassName": "h6 custom-fieldset mb-2",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "className": "row g-3 border-bottom pb-2",
                    "groupElements": [
                        {
                            "htmlElementType": "RADIO",
                            "id": "uploadFor",
                            "className": "radio-arrow",
                            "labelClassName": "col-6",
                            "values":options ,
                        }
                    ]
                }
            ],
        };
        return doctoreRegistrationForm
    }

    const getCustomerChangeRejectForm = (helpers) => {
        let rejectOptions = [];
        rejectOptions.push(helpers.createOption("PERSONAL","Wrong Personal Info","PERSONAL"));
        rejectOptions.push(helpers.createOption("Address","Wrong Address Info ","Address"));
        rejectOptions.push(helpers.createOption("CUSTOMER","Customer not requested ","CUSTOMER"));
        const rejectForm = {
            "htmlElementType": "FORM",
            "id": "rejectForm",
            "name": null,
            "value": null,
            "className": null,
            "readOnly": false,
            "disabled": false,
            "autofocus": false,
            "required": false,
            "style": null,
            "attributes": null,
            "message": null,
            "htmlActions": null,
            "elementSize": null,
            "defaultValue": null,
            "helperText": null,
            "labelClassName": "small",
            "htmlGroups": [
                {
                    "htmlElementType": "ELEMENTGROUP",
                    "id": "group1",
                    "label": null,
                    "name": null,
                    "value": null,
                    "className": "row g-3 p-12 mb-3",
                    "readOnly": false,
                    "disabled": false,
                    "autofocus": false,
                    "required": false,
                    "style": null,
                    "attributes": null,
                    "message": null,
                    "htmlActions": null,
                    "elementSize": null,
                    "defaultValue": null,
                    "helperText": null,
                    "labelClassName": null,
                    "groups": null,
                    "groupElements": [
                        {
                            "htmlElementType": "DATALIST",
                            "id": "reasonType",
                            "label": "Reason Type",
                            "name": "reasonType",
                            "value": null,
                            "onInputChangeEnable": false,
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "dataListClassName":"custom-datagrid",
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": "col-12",
                            "regex": null,
                            "minLength": null,
                            "maxLength": null,
                            "min": null,
                            "max": null,
                            "placeholder": null,
                            "hidden": false,
                            "values": rejectOptions
                        },
                        {
                            "htmlElementType": "TEXTAREA",
                            "id": "rejectReason",
                            "label": "Reason To Reject",
                            "name": "rejectReason",
                            "value": "",
                            "className": null,
                            "readOnly": false,
                            "disabled": false,
                            "autofocus": false,
                            "required": true,
                            "style": null,
                            "attributes": null,
                            "message": null,
                            "htmlActions": null,
                            "elementSize": null,
                            "defaultValue": null,
                            "helperText": null,
                            "labelClassName": null,
                            "regex": "",
                            "minLength": null,
                            "maxLength": 200,
                            "min": 1,
                            "max": null,
                            "placeholder": "Enter Reason To Reject",
                            "hidden": false
                        },
                      
                    ]
                },{

                    "htmlElementType": "ELEMENTGROUP",
                        "id": "group2",
                        "label": null,
                        "value": null,
                        "className": "modal-footer justify-content-center",
                        "readOnly": false,
                        "disabled": false,
                        "autofocus": false,
                        "required": false,
                        "style": null,
                        "attributes": null,
                        "message": null,
                        "htmlActions": null,
                        "elementSize": null,
                        "defaultValue": null,
                        "helperText": null,
                        "labelClassName": null,
                        "src": null,
                        "href": null,
                        "reset": false,
                        "submit": true,
                        "hidden": false,
                        "groupElements":[
                            {
                                "htmlElementType": "BUTTON",
                                "id": "closeModal",
                                "label": "Close",
                                "value": null,
                                "className": "ms-2 col-3 brand-secondary btn-light",
                                "readOnly": false,
                                "disabled": false,
                                "autofocus": false,
                                "required": false,
                                "style": null,
                                "attributes": null,
                                "message": null,
                                "htmlActions": null,
                                "elementSize": null,
                                "defaultValue": null,
                                "helperText": null,
                                "labelClassName": null,
                                "src": null,
                                "href": null,
                                "reset": false,
                                "submit": false,
                                "hidden": false
                            },
                            {
                                    "htmlElementType": "BUTTON",
                                    "id": "submitRejectForm",
                                    "label": "Submit",
                                    "name": null,
                                    "value": null,
                                    "className": "ms-2 col-3 btn-brand",
                                    "readOnly": false,
                                    "disabled": false,
                                    "autofocus": false,
                                    "required": false,
                                    "style": null,
                                    "attributes": null,
                                    "message": null,
                                    "htmlActions": null,
                                    "elementSize": null,
                                    "defaultValue": null,
                                    "helperText": null,
                                    "labelClassName": null,
                                    "src": null,
                                    "href": null,
                                    "reset": false,
                                    "submit": true,
                                    "hidden": false
                            }
                        ]
                }
            ],
            "notes": null,
            "atleastOneFieldRequired": false,
            "submitDisabled": true,
            "hidden": false
        };
        return rejectForm;
    }

    const onInputCustomerId = (payload, helpers, elementId) => {
        let formValue = payload[1]?.value
        if (formValue) {
            console.log(formValue)
            formValue = formValue.trim();
            if (/^[0-9]+$/.test(formValue)) {
                helpers.updateValue(formValue, elementId);
            } else {
                helpers.updateValue('', "customerId");
            }
        }
    }

    return Object.freeze({
        getCancelForm,
        getLabCancelForm,
        getAddPatientDetailsForm,
        getEditOrderDetailsForm,
        getRescheduleDeliveryForm,
        getSelectSmsForm,
        getLabOrderRefundFormForCard,
        getCFPInfoForm,
        getCustomerChangeRejectForm,
        onInputCustomerId,
        getDoctorRegistrationForm
    });

}

export default FormHelpers;
